export const cartAction = {
    ADD_ITEM_TO_CART: "ADD_ITEM_TO_CART",
    TOOGLE_CART_VIEW: "TOOGLE_CART_VIEW",
    INCREASE_CART_ITEM: "INCREASE_CART_ITEM",
    DECREASE_CART_ITEM: "DECREASE_CART_ITEM",
};
